### ISSUE TITLE
Function EXIF for store proposal

### ISSUE THREAD

**Issue by scottleedavis** [openfaas/store#100]
Hi!  I have spent some time in another OSS project writing EXIF striping code.  

This proposal is to add to the store a function that extracts and returns in JSON the EXIF information an image has if present.

https://github.com/servernull/openfaas-exif

Open to suggestions, changes and criticisms.

**Comment by alexellis** [comment]
Sound fun 👍

I'll take a look

**Comment by alexellis** [comment]
Here's my feedback and some changes you could make:

1) You need to write to os.Tempdir(), not the pwd
2) `		return "{\"error\": \"error reading image\"}"` -> you should really marshal a struct, try using an anonymous one if you don't want to add one
3) `	url := string(req)` -> perhaps it'd be better if it could also take bytes in, maybe base64 encoded? What if my files are not on the internet via a HTTP url?
4) `		os.Remove(filePath)` -> should be a defer, so that if the code crashes the file still gets deleted
5) Can you rename `openfaas-exif.yml` to `stack.yml`?
6) Remove `  gateway: http://192.168.99.104:31112` from your YAML file
7) `    image: servernull/openfaas-exif:latest` -> use a specific version 0.1.0 etc
8) `faas-cli up -f openfaas-exif.yml` -> the user can't run faas-up since your username is hard-coded, how about `faas deploy` instead in the README?
9) Can you format the example output with `jq` in README.md for readability?

Looks like a fun function for the store. 👍

**Comment by scottleedavis** [comment]
Thank you for the great feedback.  I made the updates as requested.

1,4) no filedownload happens now as it is comes from the base64.
2) anonymous structs 
3) base64 now
5,6,7,8) done
9) done.

The example now is `go run encode.go image.jpg | faas-cli invoke openfaas-exif | jq`

**Comment by alexellis** [comment]
What about?

```sh
cat image.jpg | base64 | faas-cli invoke openfaas-exif | jq
```

Could you have a mode where you check for a URL first and if it's not valid, parse as base64? Or perhaps a deployment configuration as an environment variable? Or a query-string parameter?

`?format=url`

**Comment by scottleedavis** [comment]
> What about?
> 
> ```shell
> cat image.jpg | base64 | faas-cli invoke openfaas-exif | jq
> ```

Great example, done.

> Could you have a mode where you check for a URL first and if it's not valid, parse as base64? Or perhaps a deployment configuration as an environment variable? Or a query-string parameter?

I like the first option to handle either URL or base64 image automatically by detecting a url.  Done.

Strangely, when setting up an example for the URL mode, I found it doesn't work as is.  (the OpenFaas portal works for manual invoke, or via manual stdin. 
 however piping in doesn't seem to work)
`echo https://github.com/dsoprea/go-exif/raw/master/assets/gps.jpg | faas-cli invoke openfaas-exif | jq`

 and checking the function for the failure, the url has a prefix
`parse https://github.com/dsoprea/go-exif/raw/master/assets/gps.jpg`
Thoughts?

**Comment by alexellis** [comment]
You might need to trim the input when you decide that it's a URL or use echo -n

**Comment by scottleedavis** [comment]
`echo -n` solved it.

**Comment by alexellis** [comment]
It'd be more robust if you trimmed whitespace in the Golang code too.

**Comment by scottleedavis** [comment]
Sounds good.  Done.

**Comment by alexellis** [comment]
Would you like to send a PR for the JSON files?

**Comment by scottleedavis** [comment]
Thank you for your time on this and elsewhere.

**Comment by alexellis** [comment]
Added 👍 thank you
